name = "julia_sandbox"
uuid = "b2f470b0-3331-44bb-a65b-b0754a1709c0"
authors = ["Kotaro Sonoda <kotaro1976@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
